[project]
name = "newsbot"
version = "0.1.0"
description = "Newsbot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "coverage>=7.6.12",
    "feedparser>=6.0.11",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "requests>=2.32.3",
]
